// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package llm

import (
	"context"
	"sync"
)

// Ensure, that ProviderMock does implement Provider.
// If this is not the case, regenerate this file with moq.
var _ Provider = &ProviderMock{}

// ProviderMock is a mock implementation of Provider.
//
//	func TestSomethingThatUsesProvider(t *testing.T) {
//
//		// make and configure a mocked Provider
//		mockedProvider := &ProviderMock{
//			CompleteFunc: func(ctx context.Context, req CompletionRequest) (CompletionResponse, error) {
//				panic("mock out the Complete method")
//			},
//		}
//
//		// use mockedProvider in code that requires Provider
//		// and then make assertions.
//
//	}
type ProviderMock struct {
	// CompleteFunc mocks the Complete method.
	CompleteFunc func(ctx context.Context, req CompletionRequest) (CompletionResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// Complete holds details about calls to the Complete method.
		Complete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req CompletionRequest
		}
	}
	lockComplete sync.RWMutex
}

// Complete calls CompleteFunc.
func (mock *ProviderMock) Complete(ctx context.Context, req CompletionRequest) (CompletionResponse, error) {
	if mock.CompleteFunc == nil {
		panic("ProviderMock.CompleteFunc: method is nil but Provider.Complete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req CompletionRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockComplete.Lock()
	mock.calls.Complete = append(mock.calls.Complete, callInfo)
	mock.lockComplete.Unlock()
	return mock.CompleteFunc(ctx, req)
}

// CompleteCalls gets all the calls that were made to Complete.
// Check the length with:
//
//	len(mockedProvider.CompleteCalls())
func (mock *ProviderMock) CompleteCalls() []struct {
	Ctx context.Context
	Req CompletionRequest
} {
	var calls []struct {
		Ctx context.Context
		Req CompletionRequest
	}
	mock.lockComplete.RLock()
	calls = mock.calls.Complete
	mock.lockComplete.RUnlock()
	return calls
}
